import os


def task_file_status(file_name, date, date_string):
    """If the file doesn't exist creates the file. if it exists, stores information from the file to a list in a dictionary format."""
    # If the file doesn't exist, create file
    # Otherwise open the file and read the data to task_data
    if not os.path.exists(file_name):
        with open(file_name, "w") as default_file:
            pass

    with open(file_name, 'r') as task_file:
        task_data = task_file.read().split("\n")
        task_data = [t for t in task_data if t != ""]

    # Use an empty list to store dictionaries generated by useable data from task_data
    # Each task is stored in a new dictionary
    task_list = []
    for t_str in task_data:
        curr_t = {}

        task_components = t_str.split(";")
        curr_t['username'] = task_components[0]
        curr_t['title'] = task_components[1]
        curr_t['description'] = task_components[2]
        curr_t['due_date'] = date.strptime(task_components[3], date_string)
        curr_t['assigned_date'] = date.strptime(task_components[4], date_string)
        curr_t['completed'] = True if task_components[5] == "Yes" else False

        task_list.append(curr_t)
    
    return task_list


def user_file_status(file_name, default_text):
    """If the file doesn't exist creates the file. If it exists, stores information from the file to a dictionary."""
    # If the file doesn't exist, create file
    # Otherwise open the file and read the data to user_data
    if not os.path.exists(file_name):
        with open(file_name, "w") as default_file:
            default_file.write(default_text)

    with open(file_name, 'r') as user_file:
        user_data = user_file.read().split("\n")

    # Loop through user_data and convert user login details to a dictionary
    username_password = {}
    for user in user_data:
        username, password = user.split(';')
        username_password[username] = password
    
    return username_password


def login_check(user_list):
    """Compares user input to stored data for login details. Provides access once both sets match."""
    # User provides their login details for username and password
    # First compares the username and then the password returning false and the appropriate error message if they don't match
    print("LOGIN")
    user = input("Username: ")
    curr_pass = input("Password: ")
    if user not in user_list.keys():
        print("User does not exist")
        return False
    elif user_list[user] != curr_pass:
        print("Wrong password")
        return False
    else:
        print("Login Successful!")
        return user


def main_menu(user):
    """Two different menu options are provided based on whether the user is an admin or not."""
    # Use if else statement to compare the username to check if they are the admin
    # Some extra menu items are included for the admin
    if user == "admin":
        menu = input('''\nSelect one of the following Options below:
r - Registering a user
a - Adding a task
va - View all tasks
vm - View my task
gr - Generate reports
ds - Display statistics
e - Exit

Selection: ''').lower()
    else:
        menu = input('''\nSelect one of the following Options below:
r - Registering a user
a - Adding a task
va - View all tasks
vm - View my task
ds - Display statistics
e - Exit

Selection: ''').lower()

    return menu